module.exports = (grunt) ->
  require('load-grunt-tasks')(grunt)

  `const sass = require('sass')`
  `const postcss = require('postcss')`
  `const autoprefixer = require('autoprefixer')`
  `const fs = require('fs')`

  grunt.initConfig
    pkg: grunt.file.readJSON('package.json')
    version_tag: 'v<%= pkg.version %>'
    comments: """
/*!
Chosen, a Select Box Enhancer for jQuery and Prototype
Version <%= pkg.version %>
Full source at https://github.com/jjj/chosen
Copyright (c) 2011-<%= grunt.template.today('yyyy') %> JJJ
MIT License, https://github.com/jjj/chosen/blob/master/LICENSE.md
This file is generated by `grunt build`, do not edit it by hand.
*/
\n
"""
    minified_comments: "/* Chosen <%= version_tag %> | (c) 2011-<%= grunt.template.today('yyyy') %> JJJ | MIT License, https://github.com/jjj/chosen/blob/master/LICENSE.md */\n"

    concat:
      options:
        banner: '<%= comments %>'
      jquery:
        src: ['build/chosen.jquery.js']
        dest: 'build/chosen.jquery.js'
      proto:
        src: ['build/chosen.proto.js']
        dest: 'build/chosen.proto.js'
      css:
        src: ['build/chosen.css']
        dest: 'build/chosen.css'

    copy:
      main:
        src: 'LICENSE.md'
        dest: 'build/'
      php:
        src: 'composer.json'
        dest: 'build/'
      docs:
        files: [
          {expand: true, cwd: 'build/', src: ['*.js', '*.css', '*.map', 'LICENSE.md', 'composer.json'], dest: 'docs/'}
        ]

    coffee:
      options:
        join: true
      jquery:
        files:
          'build/chosen.jquery.js': ['coffee/lib/select-parser.coffee', 'coffee/lib/abstract-chosen.coffee', 'coffee/chosen.jquery.coffee']
      proto:
        files:
          'build/chosen.proto.js': ['coffee/lib/select-parser.coffee', 'coffee/lib/abstract-chosen.coffee', 'coffee/chosen.proto.coffee']
      test:
        files:
          'spec/public/jquery_specs.js': 'spec/jquery/*.spec.coffee'
          'spec/public/proto_specs.js': 'spec/proto/*.spec.coffee'

    uglify:
      options:
        banner: '<%= minified_comments %>'
      jquery:
        options:
          mangle:
            reserved: ['jQuery']
        files:
          'build/chosen.jquery.min.js': ['build/chosen.jquery.js']
      proto:
        files:
          'build/chosen.proto.min.js': ['build/chosen.proto.js']

    sass:
      options:
        outputStyle: 'expanded'
        implementation: sass
        sourceMap: true
      chosen_css:
        files:
          'build/chosen.css': 'sass/chosen.scss'

    cssmin:
      options:
        banner: '<%= minified_comments %>'
        keepSpecialComments: 0
      main:
        src: 'build/chosen.css'
        dest: 'build/chosen.min.css'

    watch:
      default:
        files: ['coffee/**/*.coffee', 'sass/*.scss']
        tasks: ['build', 'jasmine']
      test:
        files: ['spec/**/*.coffee']
        tasks: ['jasmine']

    jasmine:
      jquery:
        options:
          vendor: [
            'docs/docsupport/jquery-3.5.1.min.js'
          ]
          specs: 'spec/public/jquery_specs.js'
        src: [ 'docs/chosen.jquery.js' ]
      jquery_old:
        options:
          vendor: [
            'docs/docsupport/jquery-1.12.4.min.js'
          ]
          specs: 'spec/public/jquery_specs.js'
        src: [ 'docs/chosen.jquery.js' ]
      proto:
        options:
          vendor: [
            'docs/docsupport/prototype-1.7.0.0.js'
            'node_modules/simulant/dist/simulant.umd.js'
          ]
          specs: 'spec/public/proto_specs.js'
        src: [ 'docs/chosen.proto.js' ]

  grunt.loadTasks 'tasks'

  grunt.registerTask 'postcss', 'Apply autoprefixer to CSS', ->
    css = fs.readFileSync('build/chosen.css', 'utf8')
    result = postcss([autoprefixer(overrideBrowserslist: ['last 1 version'])]).process(css, from: 'build/chosen.css')
    fs.writeFileSync('build/chosen.css', result.css)
    grunt.log.ok('CSS prefixed with autoprefixer')

  grunt.registerTask 'fix-sourcemaps', 'Fix sourcemap references to be relative', ->
    # Fix build sourcemap
    css = fs.readFileSync('build/chosen.css', 'utf8')
    css = css.replace(/\/\*# sourceMappingURL=build\/chosen\.css\.map \*\/$/, '/*# sourceMappingURL=chosen.css.map */')
    fs.writeFileSync('build/chosen.css', css)
    # Fix docs sourcemap
    css = fs.readFileSync('docs/chosen.css', 'utf8')
    css = css.replace(/\/\*# sourceMappingURL=build\/chosen\.css\.map \*\/$/, '/*# sourceMappingURL=chosen.css.map */')
    fs.writeFileSync('docs/chosen.css', css)
    grunt.log.ok('Fixed sourcemap references')

  grunt.registerTask 'default', ['build']
  grunt.registerTask 'build', ['coffee:jquery', 'coffee:proto', 'sass', 'concat', 'uglify', 'postcss', 'cssmin', 'copy:main', 'copy:php', 'copy:docs', 'fix-sourcemaps']
  grunt.registerTask 'test',  ['coffee', 'jasmine:jquery', 'jasmine:jquery_old']
  grunt.registerTask 'test:jquery',  ['coffee:test', 'coffee:jquery', 'jasmine:jquery', 'jasmine:jquery_old']
  grunt.registerTask 'test:proto',  ['coffee:test', 'coffee:proto', 'jasmine:proto']


