export interface ChosenOptions {
  aria_label?: string;
  allow_single_deselect?: boolean;
  placeholder_text?: string;
  placeholder_text_single?: string;
  placeholder_text_multiple?: string;
  placeholder_text_multiple_selected?: string;
  search_placeholder?: string;
  no_results_text?: string;
  no_results_template?: string;
  search_contains?: boolean;
  highlight_prefix_matches?: boolean;
  enable_split_word_search?: boolean;
  case_sensitive_search?: boolean;
  search_in_values?: boolean;
  max_search_length?: number;
  normalize_search_text?: (text: string) => string;
  search_matcher?: (query: string, item: { kind: 'option' | 'group'; label: string; value?: string }) => boolean;
  max_shown_results?: number;
  split_search_terms?: boolean;
  group_search?: boolean;
  display_selected_options?: boolean;
  deselect_selected_results?: boolean;
  hide_results_on_select?: boolean;
  display_disabled_options?: boolean;
  min_search_length?: number;
  max_selected_options?: number;
  max_items_shown?: number;
  allow_select_all?: boolean;
  allow_deselect_all?: boolean;
  paste_multiple_values?: boolean;
  search_delay?: number;
  select_all_text?: string;
  deselect_all_text?: string;
  more_items_text?: (count: number) => string;
  show_fewer_items_text?: string;
  backspace_deletes_choices?: boolean;
  single_backstroke_delete?: boolean;
  open_on_label_click?: boolean;
  multiselect_allow_tab_to_select?: boolean;
  search_input_type?: 'search' | 'text';
  disable_search?: boolean;
  disable_search_threshold?: number;
  rtl?: boolean;
  inherit_select_classes?: boolean;
  inherit_option_classes?: boolean;
  inherit_optgroup_classes?: boolean;
  parser_config?: { copy_data_attributes?: boolean };
  results_count_text?: (count: number) => string;
  display_selected_value?: boolean;
  include_group_label_in_selected?: boolean;
  create_option?: boolean | ((this: Chosen, query: string) => void);
  create_option_text?: string;
  persistent_create_option?: boolean;
  skip_no_results?: boolean;
  width?: string | number | false;
  dropdown_width?: string | number;
  dropdown_position?: 'absolute' | 'fixed';
  recalculate_width_on_update?: boolean;
}

export declare class Chosen {
  constructor(select: HTMLSelectElement, options?: ChosenOptions);
  readonly select: HTMLSelectElement;
  readonly host: HTMLElement;
  readonly input: HTMLInputElement;
  readonly opened: boolean;
  update(): void;
  open(): void;
  close(): void;
  clear(): void;
  focus(): void;
  blur(): void;
  destroy(): void;
}
export default Chosen;
